### PR TITLE
Test/git traverse

### LINKED ISSUE #268: Some tests failing on main branch
Hello, I am trying to get familiar with the project, running `make tests check-size` produce the following errors : 

```
running 9 tests
test commit::ancestor::instantiate_with_arc ... ok
test commit::ancestor::filtered_commit_does_not_block_ancestors_reachable_from_another_commit ... FAILED
test commit::ancestor::instantiate_with_box ... ok
test commit::ancestor::simple_branch_first_parent_only ... FAILED
test commit::ancestor::simple_branch_with_merge ... FAILED
test commit::ancestor::linear_history_no_branch ... ok
test commit::ancestor::predicate_only_called_once_even_if_fork_point ... FAILED
test commit::ancestor::multiple_tips ... FAILED
test tree::basic_nesting ... ok
```

Seems some object ids are not found in the store here : 
https://github.com/Byron/gitoxide/blob/3ab990ebbaf7feb999340e86933bbdc823166669/git-traverse/tests/commit/mod.rs#L48

I tried to understand what was going wrong but I am not sure how this works: 
https://github.com/Byron/gitoxide/blob/3ab990ebbaf7feb999340e86933bbdc823166669/git-traverse/tests/commit/mod.rs#L9

It is creating a fixture repository with some commit inside I get that, what I don't understand is how the object ids are set. I guess they are set somewhere since they are hard coded in the test.

### PR DESCRIPTION
**Pull request by oknozor**
- Ensure a merge commit is created in the git-traverse test fixture by adding `git config merge.ff false` in the fixture script. 
- ~~Ensure the test fixture is re-created on each test run~~
- Rename fixture directory to `generated-do-not-edit` 

closes #268

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -8,3 +8,4 @@ target/
 /tests/fixtures/repos
 
 **/generated/
+.idea
```
Comment (Byron) [inline .gitignore:11]: This belongs into `~/.gitignore`.

File: git-traverse/tests/fixtures/make_traversal_repo_for_commits.sh [hunk 2]
```diff
@@ -3,6 +3,7 @@ set -eu -o pipefail
 
 git init -q
 git config commit.gpgsign false
+git config merge.ff false
```
Comment (Byron) [inline git-traverse/tests/fixtures/make_traversal_repo_for_commits.sh:6]: Great catch, thanks for keeping at it!

File: tests/tools/src/lib.rs [hunk 3]
```diff
@@ -76,6 +76,10 @@ pub fn scripted_fixture_repo_read_only_with_args(
         .to_owned();
     let script_result_directory = fixture_path(Path::new("generated").join(format!("{}", script_identity)));
     if !script_result_directory.is_dir() {
+        if script_result_directory.exists() {
```
Comment (Byron) [inline tests/tools/src/lib.rs:79]: Some tests directories take a long time to create, sometimes up to a minute. What about renaming `"generated"` into `"generated-do-not-edit"`?

**Review by Byron — CHANGES_REQUESTED** [review]

File: .gitignore (hunk 1 above)
Comment (Byron) [reply .gitignore:11]: Forgot: https://www.toptal.com/developers/gitignore - a nice generator for all kinds of standard .gitignore files.

**Review by Byron — APPROVED** [review]
Thanks a lot for figuring out a fix, it's much appreciated!
