### PR TITLE
fix: set binary name for completions

### LINKED ISSUE #1060: Shell completion for zsh registers incorrectly
### Current behavior 😯

The completion script generated by `gix generate-completions --shell zsh` ends up with a `#compdef gitoxide` header instead of `#compdef gix`, and so is registered for the nonexistent `gitoxide` command.

This is because the `clap_complete::generate` invocation expects the actual binary name, but gets `env!("CARGO_PKG_NAME")` instead.

### Expected behavior 🤔

Shell completion script is properly formed.

### Steps to reproduce 🕹

_No response_

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Closes #1060 

```bash
shauh@specialist gitoxide 🦀±|fix_completion-bin-name ✗|→ source <(cargo run -- completions)
   Compiling gitoxide v0.31.1 (/home/shauh/gitoxide)
    Finished dev [unoptimized + debuginfo] target(s) in 13.11s
     Running `target/debug/gix completions`
shauh@specialist gitoxide 🦀±|fix_completion-bin-name ✗|→ gix
-r                    -f                    --threads             --strict              --version             commit                clone                 index                 corpus
-c                    -h                    --verbose             --progress-keep-open  archive               verify                mailmap               submodule             free
-t                    -V                    --trace               --format              commit-graph          revision              remote                config-tree           completions
-v                    --repository          --no-verbose          --object-hash         odb                   credential            attributes            status                help
-s                    --config              --progress            --help                tree                  fetch                 exclude               config
shauh@specialist gitoxide 🦀±|fix_completion-bin-name ✗|→ gix
```

### CODE REVIEW

File: src/plumbing/main.rs [hunk 1]
```diff
@@ -1221,13 +1221,17 @@ pub fn main() -> Result<()> {
         },
         Subcommands::Completions { shell, out_dir } => {
             let mut app = Args::command();
+
+            let bin_name = "gix";
+            app.set_bin_name(bin_name);
```
Comment (ShaunSHamilton) [inline src/plumbing/main.rs:1226]: This is not necessary, but could be used elsewhere if we wanted to `app.get_bin_name()`.

**Comment by Byron** [comment]
Thanks a lot, much appreciated.

I particularly like how easy it is to test the completions, thanks for the example.
